### ISSUE TITLE
API Key Sunset

### ISSUE THREAD

**Issue by briandonacion** [kerkness/wc-hub#6]
HubSpot has announced the sunset of API Key authentication for November 30, 2022.
"With the introduction of Private Apps, users who previously developed on HubSpot and utilized API Keys will now be required to migrate existing integrations from using API Key authentication to using Private Apps instead"

Will there be a new version of this plugin to keep it live and authenticate through Private Apps?
Thank you!

**Comment by kerkness** [comment]
Yes. I need to update this for my own production environment.  It's work I plan on doing in the next couple of weeks and finished early October.

**Comment by kerkness** [comment]
The next branch is working for pulling Contact details using a private app access token and v3 of the HubSpot API.

Some things of note:
- Set access token in settings for the plugin
- V3 has some differences particularly how properties are set and pulled.  

```
// Pseudo .. Instead of this ..
$contact['properties'] = [
   [ "name" => "prop_name", "value" => "prop_value" ]
];

// Use this..
$contact = [ "prop_name" => "prop_value" ]
```

**Comment by kerkness** [comment]
https://github.com/kerkness/wc-hub/releases/tag/v1.1.0

Release is ready.  Package is being built.  Will close this ticket when fully tested on my own production servers.

**Comment by kerkness** [comment]
Have been running for 18 days in production without issue.  Closing
